---
- name: services | Ensuring Guacamole Server Service Is Enabled And Starts On Boot
  service:
    name: guacd
    enabled: true
    state: started
  become: true

- name: services | Ensuring Tomcat Service Is Enabled And Starts On Boot
  service:
    name: tomcat
    enabled: true
    state: started
  become: true
